[numberformatter]
exten => s,1,NoOp(Start formatting CLID) ; log start precedure
 same => n,Set(clid=${CALLERID(num)})

 ; Remove leading 0000, +, 98, 0098 , 002198
 same => n,Set(clid=${clid:0})
 same => n,ExecIf($["${clid:0:4}"="0000"]?Set(clid=${clid:4}))
 same => n,ExecIf($["${clid:0:1}"="+"]?Set(clid=${clid:1}))
 same => n,ExecIf($["${clid:0:2}"="98"]?Set(clid=${clid:2}))
 same => n,ExecIf($["${clid:0:4}"="0098"]?Set(clid=${clid:4}))
 same => n,ExecIf($["${clid:0:6}"="002198"]?Set(clid=${clid:6}))

 ; Normalize numbers starting with 210, 21, 21098, 098
 same => n,ExecIf($[${LEN(${clid})}=13 & ${clid:0:3}=210]?Set(clid=0${clid:3}))
 same => n,ExecIf($[${LEN(${clid})}=12 & ${clid:0:2}=21]?Set(clid=0${clid:2}))
 same => n,ExecIf($[${LEN(${clid})}=15 & ${clid:0:5}=21098]?Set(clid=0${clid:5}))
 same => n,ExecIf($[${LEN(${clid})}=13 & ${clid:0:3}=098]?Set(clid=0${clid:3}))

 ; Add 0 to mobile numbers starting with 9 or 09
 same => n,ExecIf($[${LEN(${clid})}=10 & ${clid:0:1}=9]?Set(clid=0${clid}))

 ; Add 0 to OuterCity numbers < 8 digits
 same => n,ExecIf($[${LEN(${clid})}=6 | ${LEN(${clid})}=7 & ${clid:0:1} != 0]?Set(clid=0${clid}))

 ; Final CLID set
 same => n,Verbose(***** CLID Corrected From ${CALLERID(num)} to ${clid})
 same => n,Set(CALLERID(num)=${clid})
 same => n,Set(CALLERID(name)=${clid})
 same => n,Return
